import { StructuredProblem, ExecutionStep, ApproachOption } from '../types';
import { getAIManager } from './ai/AIProviderManager';
import { validateExecutionSteps } from './ExecutionStepValidator';
import { SolutionLanguage } from './ai/types';
import { DEFAULT_SOLUTION_LANGUAGE } from './ai/solutionLanguages';
import { validateGeneratedSolution } from './GeneratedSolutionValidator';
import { createResultCacheEntry } from './cache/cacheEntries';
import { createSolutionCacheIdentity, createTraceCacheIdentity } from './cache/cacheIdentities';
import { RESULT_CACHE_VERSIONS } from './cache/cacheVersions';
import { getResultCache } from './cache/resultCacheInstance';
import { InFlightRequestDeduplicator } from './cache/InFlightRequestDeduplicator';

export interface GeneratedExecutionSteps extends Array<ExecutionStep> {
  generationFeedback?: {
    truncated: boolean;
    rejectedStepCount: number;
    message?: string;
  };
  providerMeta?: {
    provider: string;
    model?: string;
    status: string;
    message?: string;
  };
}

export interface GeneratedIdealSolution {
  code: string;
  providerMeta?: GeneratedExecutionSteps['providerMeta'];
}

const buildGeneratedSteps = (
  rawSteps: unknown,
  sourceLineCount: number,
  providerMeta?: GeneratedExecutionSteps['providerMeta']
): GeneratedExecutionSteps => {
  const validation = validateExecutionSteps(rawSteps, { sourceLineCount });
  if (!validation.valid) {
    throw new Error(`Invalid step trace: ${validation.error}`);
  }

  if (validation.isTruncated) {
    console.warn(`Step trace truncated: ${validation.error}`);
  }

  const steps = validation.steps as GeneratedExecutionSteps;
  steps.generationFeedback = {
    truncated: validation.isTruncated,
    rejectedStepCount: validation.rejectedStepCount,
    message: [validation.error, validation.warning].filter(Boolean).join(' ') || undefined
  };
  steps.providerMeta = providerMeta;
  return steps;
};

export class DynamicStepGenerator {
  private static latestRequestMap: Record<string, number> = {};
  private static readonly inFlightSolutions = new InFlightRequestDeduplicator<GeneratedIdealSolution>();
  private static readonly inFlightTraces = new InFlightRequestDeduplicator<GeneratedExecutionSteps>();

  static async generateSolution(
    problem: StructuredProblem,
    approach: ApproachOption,
    language: SolutionLanguage = DEFAULT_SOLUTION_LANGUAGE,
    signal?: AbortSignal
  ): Promise<GeneratedIdealSolution> {
    const aiManager = getAIManager();
    if (!aiManager) throw new Error('AI Manager not initialized.');

    const key = `${problem.id}:${approach.id}:${language}:generateSolution`;
    DynamicStepGenerator.latestRequestMap[key] = (DynamicStepGenerator.latestRequestMap[key] || 0) + 1;
    const reqId = DynamicStepGenerator.latestRequestMap[key];
    const requestOptions = {
      task: 'steps',
      signal,
      solutionLanguage: language
    };
    const target = aiManager.getRequestTarget(requestOptions);
    const identity = await createSolutionCacheIdentity(problem, approach, language, target);
    const cache = getResultCache();
    const cached = await cache.lookup(identity, false, (payload) => validateGeneratedSolution(payload, language).valid);

    if (cached.hit) {
      if (DynamicStepGenerator.latestRequestMap[key] !== reqId || signal?.aborted) {
        const error: any = new Error('AbortError');
        error.name = 'AbortError';
        throw error;
      }
      const solution = validateGeneratedSolution(cached.entry.payload, language);
      if ('error' in solution) throw new Error(`Invalid cached solution: ${solution.error}`);
      return {
        code: solution.solution.code,
        providerMeta: {
          provider: cached.entry.producerProvider,
          model: cached.entry.producerModel,
          status: 'cached',
          message: `Loaded cached code generated by ${cached.entry.producerProvider}.`
        }
      };
    }

    const generated = await DynamicStepGenerator.inFlightSolutions.run(
      identity.fullKey,
      signal,
      async (sharedSignal) => {
        const { data, meta } = await aiManager.generateSolution(
          problem, approach, { ...requestOptions, signal: sharedSignal }
        );
        cache.store(createResultCacheEntry({
          identity,
          layer: 'solution',
          versions: RESULT_CACHE_VERSIONS,
          producerProvider: meta?.provider || target.provider,
          producerModel: meta?.model || target.model,
          payload: data
        }));
        return { code: data.code, providerMeta: meta };
      }
    );

    if (DynamicStepGenerator.latestRequestMap[key] !== reqId || signal?.aborted) {
      const error: any = new Error('AbortError');
      error.name = 'AbortError';
      throw error;
    }

    return generated;
  }

  static async generate(
    problem: StructuredProblem,
    approach: ApproachOption,
    solutionCode: string,
    testCase: { input: string; output: string },
    language: SolutionLanguage = DEFAULT_SOLUTION_LANGUAGE,
    signal?: AbortSignal
  ): Promise<ExecutionStep[]> {
    const aiManager = getAIManager();
    if (!aiManager) throw new Error("AI Manager not initialized.");

    const key = `${problem.id}:generate`;
    DynamicStepGenerator.latestRequestMap[key] = (DynamicStepGenerator.latestRequestMap[key] || 0) + 1;
    const reqId = DynamicStepGenerator.latestRequestMap[key];

    if (signal?.aborted) {
      const err: any = new Error('AbortError');
      err.name = 'AbortError';
      throw err;
    }

    const sourceLineCount = solutionCode.split(/\r?\n/).length;
    const requestOptions = {
      task: 'steps',
      signal,
      sourceLineCount,
      solutionLanguage: language
    };
    const target = aiManager.getRequestTarget(requestOptions);
    const identity = await createTraceCacheIdentity(
      problem, approach.id, language, solutionCode, testCase, 'ideal', target
    );
    const cache = getResultCache();
    const cached = await cache.lookup<ExecutionStep[]>(identity, false, (payload) => (
      validateExecutionSteps(payload, { sourceLineCount }).valid
    ));

    if (cached.hit) {
      if (DynamicStepGenerator.latestRequestMap[key] !== reqId || signal?.aborted) {
        const err: any = new Error('AbortError');
        err.name = 'AbortError';
        throw err;
      }
      return buildGeneratedSteps(cached.entry.payload, sourceLineCount, {
        provider: cached.entry.producerProvider,
        model: cached.entry.producerModel,
        status: 'cached',
        message: `Loaded a cached trace generated by ${cached.entry.producerProvider}.`
      });
    }

    const steps = await DynamicStepGenerator.inFlightTraces.run(
      identity.fullKey,
      signal,
      async (sharedSignal) => {
        const { data: rawSteps, meta } = await aiManager.generateSteps(
          problem, solutionCode, testCase, { ...requestOptions, signal: sharedSignal }
        );
        const generatedSteps = buildGeneratedSteps(rawSteps, sourceLineCount, meta);
        cache.store(createResultCacheEntry({
          identity,
          layer: 'trace',
          versions: RESULT_CACHE_VERSIONS,
          producerProvider: meta?.provider || target.provider,
          producerModel: meta?.model || target.model,
          payload: [...generatedSteps]
        }));
        return generatedSteps;
      }
    );

    // Ignore if a newer request started
    if (DynamicStepGenerator.latestRequestMap[key] !== reqId) {
      const err: any = new Error('AbortError');
      err.name = 'AbortError';
      throw err;
    }

    return steps;
  }

  static async generateFromUserCode(
    problem: StructuredProblem,
    userCode: string,
    testCase: { input: string; output: string },
    language: SolutionLanguage = DEFAULT_SOLUTION_LANGUAGE,
    signal?: AbortSignal
  ): Promise<ExecutionStep[]> {
    const aiManager = getAIManager();
    if (!aiManager) throw new Error("AI Manager not initialized.");

    const key = `${problem.id}:${language}:generateFromUserCode`;
    DynamicStepGenerator.latestRequestMap[key] = (DynamicStepGenerator.latestRequestMap[key] || 0) + 1;
    const reqId = DynamicStepGenerator.latestRequestMap[key];

    if (signal?.aborted) {
      const err: any = new Error('AbortError');
      err.name = 'AbortError';
      throw err;
    }

    const sourceLineCount = userCode.split(/\r?\n/).length;
    const requestOptions = {
      task: 'steps',
      signal,
      sourceLineCount,
      solutionLanguage: language
    };
    const target = aiManager.getRequestTarget(requestOptions);
    const identity = await createTraceCacheIdentity(
      problem, null, language, userCode, testCase, 'user-code', target
    );
    const cache = getResultCache();
    const cached = await cache.lookup<ExecutionStep[]>(identity, false, (payload) => (
      validateExecutionSteps(payload, { sourceLineCount }).valid
    ));

    if (cached.hit) {
      if (DynamicStepGenerator.latestRequestMap[key] !== reqId || signal?.aborted) {
        const err: any = new Error('AbortError');
        err.name = 'AbortError';
        throw err;
      }
      return buildGeneratedSteps(cached.entry.payload, sourceLineCount, {
        provider: cached.entry.producerProvider,
        model: cached.entry.producerModel,
        status: 'cached',
        message: `Loaded a cached trace generated by ${cached.entry.producerProvider}.`
      });
    }

    const steps = await DynamicStepGenerator.inFlightTraces.run(
      identity.fullKey,
      signal,
      async (sharedSignal) => {
        const { data: rawSteps, meta } = await aiManager.generateSteps(
          problem, userCode, testCase, { ...requestOptions, signal: sharedSignal }
        );
        const generatedSteps = buildGeneratedSteps(rawSteps, sourceLineCount, meta);
        cache.store(createResultCacheEntry({
          identity,
          layer: 'trace',
          versions: RESULT_CACHE_VERSIONS,
          producerProvider: meta?.provider || target.provider,
          producerModel: meta?.model || target.model,
          payload: [...generatedSteps]
        }));
        return generatedSteps;
      }
    );

    if (DynamicStepGenerator.latestRequestMap[key] !== reqId) {
      const err: any = new Error('AbortError');
      err.name = 'AbortError';
      throw err;
    }

    return steps;
  }
}
